In [1]:
from rank_bm25 import BM25Okapi

from transformers import AutoTokenizer
import numpy as np

In [2]:
def simple_tokenize(doc: str):
    return doc.split(" ")

In [3]:
corpus = [
    "hello there good man!",
    "it is quite windy in london",
    "how is the weather today?"
]

query = "windy london"

In [4]:
bm25 = BM25Okapi([simple_tokenize(doc) for doc in corpus])

In [13]:
scores = bm25.get_scores(simple_tokenize(query))
scores

array([0.        , 0.93729472, 0.        ])

In [14]:
np.argmax(scores)

np.int64(1)

In [17]:
np.argpartition(scores, 0)

array([0, 2, 1])

In [ ]:
model_id = "amd/AMD-OLMo-1B-SFT"

In [6]:
tokenizer = AutoTokenizer.from_pretrained(model_id, return_tensors="pt")

In [7]:
model_tokenized_corpus = [tokenizer.encode(doc) for doc in corpus]

In [8]:
model_tokenized_bm25 = BM25Okapi(model_tokenized_corpus)

In [19]:
model_tokenized_scores = model_tokenized_bm25.get_scores(tokenizer.encode(query))
model_tokenized_scores

array([0.        , 1.37021461, 0.        ])

In [20]:
np.argmax(model_tokenized_scores)

np.int64(1)

In [21]:
np.argpartition(model_tokenized_scores, 0)

array([0, 2, 1])